version: '3'

services:

  web:
    container_name: qmeter-bot
    build: .
    restart: "always"
    command: ["uwsgi", "--ini", "/code/uwsgi.ini"]
#    command: daphne --bind 0.0.0.0 --port 8050 aqms.asgi:application
    env_file: .env
    environment:
      - VIRTUAL_PORT=8022
      - TIMEOUT=300
      - HTTP_PORT=8022
      - STATS_PORT=8051
      - LANG=C.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8
    volumes:
      - .:/code
      - ./media:/code/media
      - ./static:/code/static
    ports:
      - "8022:8022"

